# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PowerTools-Upload-Blob
version:      0.01
version_from: lib/PowerTools/Upload/Blob.pm
installdirs:  site
requires:
    DBI:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
